version: "3.8"

services:
  app:
    build: .
    container_name: mnist_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mnist_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=MLI_Project_Work

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mnist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MLI_Project_Work
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
